source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'example' do
  rn_path = '../../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path

  pod 'NearbyMessages', '1.1.0'
  pod 'react-native-nearby-api', :path => '../node_modules/react-native-maps'
end
