source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'RNNearbyApi' do
    pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
    pod 'React', path: '../node_modules/react-native'
    pod 'NearbyMessages', '1.1.0'
end
